version: "3.8"

services:
  app:
    build: .
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
    restart: always
    networks:
      - local
  nginx:
    build:
      context: ./nginx
      args:
        SERVICE_NAME: app
        PORT: ${PORT}
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - <PATH_TO_CERTIFICATE_ON_HOST_MACHINE>:/etc/letsencrypt/live/2048.botify.com
    depends_on:
      - app
    networks:
      - local

networks:
  local:
    driver: bridge
